services:
  nats-server:
    image: nats:2.11.6-alpine3.22
   
  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    image: client-gateway-prod
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222
# ========================
# Auth Microservice
# ========================
  auth-ms:
    image: auth-ms
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASEURL}
      - JWT_SECRET=${JWT_SECRET}

  products-ms:
    image: products-ms
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
      args:
        - PRODUCTS_DATABASE_URL=${PRODUCTS_DATABASE_URL}
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      # - DATABASE_URL=file:/usr/src/app/prisma/dev.db
      - DATABASE_URL=${PRODUCTS_DATABASE_URL}

# ========================
# Payments Microservice
# ========================
  payments-ms:
    image: payments-ms
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${PAYMENTS_MS_STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${PAYMENTS_MS_STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${PAYMENTS_MS_STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${PAYMENTS_MS_STRIPE_ENDPOINT_SECRET}

# ========================
# Orders Microservice
# ========================
  orders-ms:
    image: orders-ms
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}